hash-format = "sha256"

[[files]]
file = "config/advancedbackups-client.pw.toml"
hash = "8a567537ecee7a1d17d3eda7e16c95f666e109d8c8b1c536185749cea844ca40"
metafile = true

[[files]]
file = "config/advancedbackups-server.pw.toml"
hash = "25511bf9fac229bb24383fed5b30830073f49d172d49707a078bb40014de52fa"
metafile = true

[[files]]
file = "config/uncrafter.jsonc"
hash = "8916f1e9f36cfe6f6d60dc2348e7787fae0f2f05aec5912a92127978c5bb8ccb"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "cd9d19c271be70eb64a57e655813aa6071b8e30babf669ec0b6c23d7cefbc328"
metafile = true

[[files]]
file = "mods/advanced-backups.pw.toml"
hash = "a9abbbbdb93dffea97154d73be989aa8d8322bca34fdac84309c7e37fc40f46b"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "53d0df42486615aebef2b0b14813e9e7cdc590d15f42c35ca29f213359b73bf1"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "546f08a8e9d566fc2da92eef04a7053eb4e1a2c39103aacf55031c5f0683b234"
metafile = true

[[files]]
file = "mods/applied-energistics-2-wireless-terminals.pw.toml"
hash = "3c326ad15adc2d077e1b5b60d43122dade0e134c28a730b208a6b491eefec025"
metafile = true

[[files]]
file = "mods/applied-mekanistics.pw.toml"
hash = "2bb6f8504bebe2b232685a2b7c975ab0c0c6792f86b5b2dcdd504b1d280e435f"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea904f09ccf8c8a6e92058c6e6d5bdca15d0d46cc8a2844bbcf1852e6e1e0326"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "813c9007db105e9ff7d982c44cff3093d7a602270131412e7a3ecfac24bf5608"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "3ae6b20e711e7dca104a9de95d79f43d70ba6b301d36f10f6fe813befc678dac"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "f9e93a1e9a4e4d9e99993a689072fff5e7bd04a50620fbfc8f5664d4a7f327f5"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "923307316761a678457c4f90ff63f1e564ba27020128f56b472ac6fc3a8c6888"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "aaaad7f3ec3924e012be36b0ebb405cb991db43a0e1ccb8654ef26cfcb745696"
metafile = true

[[files]]
file = "mods/configured.pw.toml"
hash = "e3753910e6cd57faaa50cb0670b8f5e38cbe129d382ef5c3df449fb88a972cca"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "2a033edcfafd7686d5adc637a171c1ab127b75dc9ab94cee11a3e24ef9428637"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "10166cb3e88f680ddb2c96d5df1f2e6baac640dc30822cb37a313ee81cd9bdc5"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "8cea6a7ec6b151f92a3a62261530bb1aefe173ad19840c0319aa10e0d8ab2386"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "46f46f8c3c47095e438cd03e7e463a4be62bd169cbcef530dadf66dc3b523f15"
metafile = true

[[files]]
file = "mods/crafting-tweaks.pw.toml"
hash = "055f68ba57069f079b90176807b55dd43f3b41aa1bed4b303ab2ffb05fca609f"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "fb4e28742d952121ba3f7ad813ca128a0121d969c5d04832eb59567cdb2ff80d"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "e70e53bf39cafbe808ab16620f4e58398efd9177fa9667d60d8e9cc12703ed6d"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "97fb8d2960cbe5be3edef398613f43a8d922575633c4b8ac88a4a0825e5a1ab8"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "2b1d554b91d33984e1ef37b5487bcbb20ad7ad4e46ba6f008987d06195915bff"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "6fa6b3f071d106ea428d5b80c6cecf1cc906ab91461046b2d67a822a43f27fe8"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "dbb78ad572330a111a703548cea3df9b99247711476c33e9acab66c4a32af19f"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "83ac3e7f70eb567845286596a8baad96b73ef3c2ee1fa378375df7a13aad7c11"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "6ab8663a916d6b2c8704c5597f57980e5626bd3cbc93420cd2d5dbce44f1a690"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "2356fdd1f2f6cf209194548a4e708031e9ad311c595dd1b6e1e0afe9cd7e990d"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "d322003d4a2c2b8b99904f33f3d70713836c5aec79f14d37dee0487bc9619a70"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "94a0f9a8d98b08b84364630f72bb45c70eda5440857a3ca373c93129afd4e572"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "6a29e340290caa00f755358ca19cafbcdcb6913747e97e0dcd6f5c95b0bd470d"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "ad3569b369ada928085b9f1a265a80f7a4315cb6571d67210545cb39fd1546e6"
metafile = true

[[files]]
file = "mods/just-enough-professions-jep.pw.toml"
hash = "4e389388869a42c989bc1c58c36e417b4020f822b5f4dfc6daef8d3e620368b7"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "36fc29ab2ffc1a38e7f8aefd098cf92bf3ce253630ef81d8a64d00ab8facf542"
metafile = true

[[files]]
file = "mods/justenoughbreeding.pw.toml"
hash = "db9db68536c179b17a6aa8d5dd7a63c78530e64b182163444d51b15adec21678"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "7ea985404ee4cc9082472c6869ec146309f526e395361b39f2f4c1a43506c41d"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "74843219d7c6f3fd110e5c3e0e858b945851682c874f2838535fc926d33a431e"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "e6df5a4fa678c73392f97a814406f810ac767196907069255b2f0eb389647455"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "5cd4fac24a62dfa6334eade67c93252984f717775ce646205cf2281cbc815fea"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "65c0fa60552afc094ccd00e0b18f33061260fd979d8e8b263b984170f1d60598"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
hash = "980dbe43fbf64938dc871bb5ed6736aef634f306bb120e6e36d46cea4205395c"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "6743dd4777df9c531bce408fe43255f97b068ad65d24ade81c447606f89a8916"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "963e1eb6cfa6d91438288ee3776ba06ea62d202039ba5a79620c9864ed8ec5fc"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "73bbc6c3cdc20c6c08dd291689274bec0055e993a37087634add21c9461fe981"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "36203fc0dc6e05fc04ccbdc5cc180f0881e6926eda82d4836a9b67623d2d7f9b"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "f83b253ca6a8e6f2f847952704da0e1fb00e65cbb10b7c9cb15d1a1780618da0"
metafile = true

[[files]]
file = "mods/odyssey-allies.pw.toml"
hash = "96f71d94809e42cc8b7ff3b2e4f6e38284ed2c89465758548bd54f726d6e1381"
metafile = true

[[files]]
file = "mods/odyssey-claims.pw.toml"
hash = "a858dd9954aa4c1db4eaad9399ec8297cf7d9aced1a404a43abc263baf45666b"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "d10bd3ce815ea1980e944c618855a63e5feaddbf0a6327e82ad6ec7a7d573a2e"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "28bac41f602e2ea0689dbfbe9998658829bf45b35207820c2465b783732d2992"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "84be1d17c5aaa19f50b157fc11a18ea0122d0868342484cdafcf2b48e89602dc"
metafile = true

[[files]]
file = "mods/radium.pw.toml"
hash = "bbdd40b650286973d44b1931d4b8c4bcc02b02f2c5583545709347503bd13057"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "a82c30811cec8872f8b5fd074c81d77fe04388321badfb8bdd9a60235c642b8c"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "d9e52716e9f1bdb855ac4d01e727b96197f177f60529a3f3fe40dfb56b696ff7"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
hash = "f90239ab37812106e86a27cf2bdf52b2002e4c331d4ccb7fb1fc9bc2197f5999"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "92efbf89bde954bfec03b7c0ce3726a2c6006b63f66f4759d64494e4f12b8601"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "82bb7cd6c8b68bb1831bb7c374bd316b6403cd01195d582f19c31076c908953a"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "75a60e6b443b351b7a4a78ffce7c71e44b3e20ca10c374aea1de516c785d6e2d"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "ef8139cbad294efe36e3c82c883098df233faadc3003475b1f92a846a91086a4"
metafile = true

[[files]]
file = "mods/speedometer.pw.toml"
hash = "e122de2d6723309d12d630107881d69601efe503bffd89507b2550fc3ab59e43"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "6cd1e15b58c4fd79154ea448a783c26c1f727f9d7ab1e2edc29788f94989086f"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "3b61fcf1c80cfdd79282be71ddfa9cce02fc13f8d87a760db455e2a97b801f40"
metafile = true

[[files]]
file = "mods/uncrafter.pw.toml"
hash = "f463a28d818796d2e6760a4c686022ff7c4fc4486db48b9c0745f6ad354ba8d2"
metafile = true

[[files]]
file = "mods/zume.pw.toml"
hash = "417f2ce9f6018e0ce5b548c4e3212abe3d74878654dd2a8a057d54c334d5b188"
metafile = true
