hash-format = "sha256"

[[files]]
file = "config/advancedbackups-client.pw.toml"
hash = "8a567537ecee7a1d17d3eda7e16c95f666e109d8c8b1c536185749cea844ca40"
metafile = true

[[files]]
file = "config/advancedbackups-server.pw.toml"
hash = "25511bf9fac229bb24383fed5b30830073f49d172d49707a078bb40014de52fa"
metafile = true

[[files]]
file = "config/uncrafter.jsonc"
hash = "8916f1e9f36cfe6f6d60dc2348e7787fae0f2f05aec5912a92127978c5bb8ccb"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "7b5fba1b2499c191160be6b1b01c54ace077ae7d3c5228ae4af4d360e3d0a336"
metafile = true

[[files]]
file = "mods/advanced-backups.pw.toml"
hash = "6ff0459e53f8bc6d77862c242f96b321db7d99cc27398ced9cf7c94a39814ad0"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "ed45c352a49b65c7221e57d979d0c6935522dfef4968aa5b7421f4d3e670ce40"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3213c881d019cd8f952f738c10d5a950ee52ff0084750b81f656a58a4a78515d"
metafile = true

[[files]]
file = "mods/applied-energistics-2-wireless-terminals.pw.toml"
hash = "4d93d1bc2eeb8c41e3d275d832b4d3eb17578414caf468aced7241ef2e58242a"
metafile = true

[[files]]
file = "mods/applied-mekanistics.pw.toml"
hash = "bd25db756e368a27d83240e4345e4cc26d0237943ef0ca56603db1de4e0818f3"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "e53392cab6393798f95c4ad012dcbd9a5a55d02ef2861ac0c23bee972686dddc"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "95322b6e88dbeba91b5e7a30d6bd011629124ae8aef5bf1b7d1304f12bd4619c"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "c9aca350959a8936b054c7164fb55d789ab1e0d38cff2af48b78f70af2bc0c6d"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "8629fe0739a2243641a1a00b103682bcb2741a9295f9eac4c2a2135a867f8442"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/configured.pw.toml"
hash = "74705ad5043cf5866d0b558e9cded4b78eaf12afc2f78ab12c0863cc2d4c54d0"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "3b247848879885198f4831d9430267abfc2242d47a1f1ff22327490ede940fb1"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "c02be4e5eb99c4b12167fa80e14d9a196d507c8964dd545ec685c15cf9c5bfa0"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "2e082857985c7550efdad38a1997b9805051b07fb61b0cd30921e786a8521130"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "65c8086d2ec3d39acc7bd36c7a0306ccc43b602b38fa07d13291bc478ef7dfff"
metafile = true

[[files]]
file = "mods/crafting-tweaks.pw.toml"
hash = "88f0ed2720f25b03440898c6f953bb50e709fc9f5af6cd376b98977b1d40c275"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "3f8fb0012b658c3ed2dfcde1385aa6255ee46cd18b77975d68665aaf0ee2a94d"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "975f1280c712d2e86dd4ecddf89c516afbf3f1fb684499d3e5c71fc666c4888c"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "774831f9dc9f530416b2d71ed08d52502dd6ccacbe4bd0d16adbf23701ce12bc"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "c67d73440c55cc47a47ac8987da9cd01de3ad2a8f1480a304355c3e21092d2e4"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "b062d71c371b3361e700edb4db46acd1a1feed6c91b95764e08e03cdb25ba1f5"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "5b284dff8a784697777570efd63877e3d625e3bfe6dcaa5b2d24390fae143aa1"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "b8aee2057378b6f054f94550684d9a3f41ded7cc47794c8b01c107c8c2115ceb"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "27af2f251af4cb0fee230499676de2c8d4cd72337dcc10cedddbae5d599007e2"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "cc903c56f854019dc420ab9a088e1a3a328e7839291aafae038f37005e59988e"
metafile = true

[[files]]
file = "mods/just-enough-professions-jep.pw.toml"
hash = "ead018f3794f086abf4acb238c2f99abf465fc27f002483083ba5809e02afa54"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "7905c08f37d8ebde50a5330a7dd10029de6259b0cb8adbde1170d93ea20218a7"
metafile = true

[[files]]
file = "mods/justenoughbreeding.pw.toml"
hash = "2814d0d33ca5a6b95da1084b954eca9ca627890455c788811351ad6069a8f3bf"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1a9ec5beaba1be3151b8710db2bfab90c2063a4dafaf2720336852245a145cc4"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "6917553073df67745da1d535cc6107839a76b54081b1b6f368a38c723f5fd8c7"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "5ce96ac040fca257f41959be41ad80ba790102dc91cccd8c09e81eed19fa6478"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "f199fe36b913131dfa2d31ec4a03186aa00be227f7fe2e34c4c3064b8601bb99"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
hash = "bf4de668aa7c3811275080a313dd1fd8d02ed3f1eaf2e71ed6ac06309a47e46b"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "a91218ff2e9980ce5ad3eb48ae211e3c0b23fb2a82a906e1059a49286a04249f"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "ccd8fcec866d3a283d2f58e44eb1a2174fb0f480fc6039ba144156e147e082d8"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "eae3c14c915400de36bf547550f630de727bbf48ae0ce719b99b2ff50ceaab0d"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5da18814472be5dc93a21886983646da3a7236413800075ac75229be82d114fa"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "04ba8a8c91a6c25c42321493a2d233762bb01169fac5fd834e434887cdbf8596"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "152769b5dfbb92a836634e315898b23b6a555c60b6f05ddf38c00085f2b784f6"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "6812c3faa178cd48c65c5b8e7aeef50bc0b63d8e3b2117065d6179a43d8d3649"
metafile = true

[[files]]
file = "mods/radium.pw.toml"
hash = "1375600837a536424b4e99878da81bc126ad8a1b962b6dea8e38c245b124e143"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "09306b955060349986ccf6a6d2a67f1e019fa172a7dc690dd6007f81c966309a"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "27721caca5a03b743bf25888e1d984142948069dace31453f103f94f7f24d2ce"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "c0b066684294c33972d562e0cb08ea17b2d31bcf86cd1d6c63b8e968f0eac7a2"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "ce9ddada6ffd55a512149cc474c6a453281a997a5fdf1b7b4a2cc73f875e704a"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "c1e526d3d17cb3563e596d45c7567ed1fe60c31bdc3457f7a747ef8150bd3c1b"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "d193173f0f5dfb4a921d44e29e8d5cee656dd3a40872939069715bb482b66fc9"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "258a77de0a6db4c9ab045cbb240bcf4eac0dbbca3f6bc981fb461e55c247f23f"
metafile = true

[[files]]
file = "mods/speedometer.pw.toml"
hash = "86c935758175880c2c382e57d7e5148c5cebfe2fbe86fe63e524ae1e9b404dd6"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "8ad02530347f7b0dfe84b8eb081e2eaa23cae536de0d289137902f7557fb3a33"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "da7ee99189ad35aac094919fe33cac647d98533b23c228f10d4811f08989e2b8"
metafile = true

[[files]]
file = "mods/zume.pw.toml"
hash = "417f2ce9f6018e0ce5b548c4e3212abe3d74878654dd2a8a057d54c334d5b188"
metafile = true
