name = "Lightly Modded Forge"
author = "brakenium"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "212acc90dcf380559323ba4a10c5d14a1bb7de46971f325a0295d27bb6b70097"

[versions]
minecraft = "1.20.4"
neoforge = "20.4.251"
